---
apiVersion: v1
kind: Service
metadata:
  name: sqrtLooper
  labels:
    app: sqrtLooper
spec:
  type: NodePort
  selector:
    app: sqrtLooper
  ports:
    - protocol: TCP
      port: 9999
      name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sqrtLooper
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: sqrtLooper
    spec:
      containers:
        - name: sqrtLooper
          image: webberlh/sqrt-looper
          imagePullPolicy: Never
          ports:
            - containerPort: 9999
          livenessProbe:
            httpGet:
              path: /metric
              port: 9999
            initialDelaySeconds: 30
            timeoutSeconds: 1