---
apiVersion: v1
kind: Service
metadata:
  name: sqrt-looper
  labels:
    app: sqrt-looper
spec:
  type: NodePort
  selector:
    app: sqrt-looper
  ports:
    - protocol: TCP
      port: 9999
      name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sqrt-looper
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: sqrt-looper
    spec:
      schedulerName: extended-default-scheduler
      containers:
        - name: sqrt-looper
          image: 10.0.0.100:5000/webberlh/sqrt-looper:latest
          ports:
            - containerPort: 9999
          livenessProbe:
            tcpSocket:
              port: 9999
            initialDelaySeconds: 30
            timeoutSeconds: 20
            periodSeconds: 30